import ActiveProjects from './activeProjects';
import Balance from './balance';
import Benefits from './benefits';
import ChevronDown from './chevronDown';
import CollapseAll from './collapseAll';
import Dashboard from './dashboard';
import Edit from './edit';
import ExpandAll from './expandAll';
import FileExcelOutlined from './fileExcelOutlined';
import LoadingAnimation from './loadingAnimation';
import PhaseGate from './phaseGate';
import Priority from './priority';
import ProjectBudget from './projectBudget';
import ProjectOverall from './projectOverall';
import ProjectQuality from './projectQuality';
import Projects from './projects';
import ProjectSchedule from './projectSchedule';
import ProposalsInProgress from './proposalsInProgress';
import Reports from './reports';
import ReportsPaid from './reportsPaid';
import Resources from './resources';
import Settings from './settings';
import TotalCapitalExpenses from './totalCapitalExpenses';
import TotalCost from './totalCost';
import TotalFinancialBenefit from './totalFinancialBenefit';
import TotalOperationalExpenses from './totalOperationalExpenses';
import TotalPortfolioCost from './totalPortfolioCost';
import TotalRevenue from './totalRevenue';
import WorkIntake from './workIntake';
import WorkIntakePaid from './workIntakePaid';

export const activeProjects = ActiveProjects;
export const balance = Balance;
export const benefits = Benefits;
export const chevronDown = ChevronDown;
export const collapseAll = CollapseAll;
export const dashboard = Dashboard;
export const edit = Edit;
export const expandAll = ExpandAll;
export const fileExcelOutlined = FileExcelOutlined;
export const loadingAnimation = LoadingAnimation;
export const phaseGate = PhaseGate;
export const priority = Priority;
export const projectBudget = ProjectBudget;
export const projectOverall = ProjectOverall;
export const projectQuality = ProjectQuality;
export const projects = Projects;
export const projectSchedule = ProjectSchedule;
export const proposalsInProgress = ProposalsInProgress;
export const reports = Reports;
export const reportsPaid = ReportsPaid;
export const resources = Resources;
export const settings = Settings;
export const totalCapitalExpenses = TotalCapitalExpenses;
export const totalCost = TotalCost;
export const totalFinancialBenefit = TotalFinancialBenefit;
export const totalOperationalExpenses = TotalOperationalExpenses;
export const totalPortfolioCost = TotalPortfolioCost;
export const totalRevenue = TotalRevenue;
export const workIntake = WorkIntake;
export const workIntakePaid = WorkIntakePaid;
